//login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGGOUT = "LOGGOUT";
export const APP_LOADED = "APP_LOADED";
export const GET_DEVICE_ID_SUCCESS = "GET_DEVICE_ID_SUCCESS";
export const SELECT_REGION = "SELECT_REGION";
export const CHECK_IS_USED = "CHECK_IS_USED";

//api
export const FETCH_LIST_ITEM = "FETCH_LIST_ITEM";
export const FETCH_SUCCEEDED = "FETCH_SUCCEEDED";
export const FETCH_FAILED = "FETCH_FAILED";

export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";
export const FETCH_LIST_CATEGORY_SUCCESS = "FETCH_LIST_CATEGORY_SUCCESS";
export const FETCH_LIST_CATEGORY_FAILED = "FETCH_LIST_CATEGORY_FAILED";

//list ads
export const ON_END_READ = "ON_END_READ";
export const GET_LIST_ADS_WITH_NEW_CATEGORY = "GET_LIST_ADS_WITH_NEW_CATEGORY";
export const GET_LIST_ADS_ON_END_READ = "GET_LIST_ADS_ON_END_READ";
export const GET_LIST_ADS_ON_REFRESH = "GET_LIST_ADS_ON_REFRESH";

export const CLICK_ADD = "CLICK_ADD";

export const COMPARE_OWN = "COMPARE_OWN";
export const TO_BE_COMPARE = "TO_BE_COMPARE";

//list Item Screen
export const CLICK_FILTER_CATEGORY = "CLICK_FILTER_CATEGORY";
export const CLICK_FILTER_AREA = "CLICK_FILTER_AREA";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const POST_EVENT_CLICK = "POST_EVENT_CLICK";
export const POST_EVENT_LOAD = "POST_EVENT_LOAD";

export const FETCH_LIST_ADS_RECOMMAND = "GET_LIST_ADS_RECOMMAND";
export const FETCH_RECOMMAND_SUCCESS = "FETCH_RECOMMAND_SUCCESS";
export const FETCH_RECOMMAND_FAILED = "FETCH_RECOMMAND_FAILED";

export const FETCH_DETAIL_AD = "FETCH_DETAIL_AD";
export const FETCH_DETAIL_AD_SUCCESS = "FETCH_DETAIL_AD_SUCCESS";
export const FETCH_DETAIL_AD_FAILED = "FETCH_DETAIL_AD_FAILED";

export const LOAD_FONT_FAMILY = "LOAD_FONT_FAMILY";
export const LOAD_FONT_SUCCESS = "LOAD_FONT_SUCCESS";
export const LOAD_FONT_FAILED = "LOAD_FONT_FAILED";

//action app
export const READ_MORE = "READ_MORE";
export const READ_LESS = "READ_LESS";

export const CLICK_CATEGRORY = "CLICK_CATEGRORY";
